[package]
name = "lygre"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.41.0"
glam = "0.17.3"

[dependencies.gltf]
version = "0.16"
features = ["extras", "names"]
